provider:
  name: test
  extension: "cql"
  params:
    database: executor
    table: cassandra_migrations

executor:
  source: "$HOME/dev/projects/data-pipelines/typeboot/typeboot-spec/output/cql"
  provider:
    name: test
    extension: "sql"
    params:
      driver: org.postgresql.Driver
      host: "127.0.0.1"
      port: "5432"
      username: postgres
      password: password
      app_name: "core"