provider:
  name: jdbc
  extension: "sql"
  separator: ";"
  params:
    driver: "org.postgresql.Driver"
    host: "127.0.0.1"
    port: "5432"
    username: "postgres"
    password: "password"
    database: executor
    table: jdbc_migrations

executor:
  source: "$HOME/dev/projects/data-pipelines/typeboot/typeboot-spec/output/sql"
  provider:
    name: jdbc
    extension: "sql"
    separator: ";"
    params:
      driver: org.postgresql.Driver
      host: "127.0.0.1"
      port: "5432"
      username: postgres
      password: password
      app_name: "core"
      team_name: "default"
