provider:
  name: jdbc
  params:
    driver: "com.postgresql.Driver"
    host: "127.0.0.1"
    port: "5432"
    username: "postgres"
    password: "password"

executor:
  params:
    driver: com.postgresql.Driver
    host: "127.0.0.1"
    port: "5432"
    username: postgres
    password: password
    database: executor
    table: mysql_migrations
